id = "java-launcher"
name = "Java Launcher"
version = "1.5.0"
schema_version = 1
description = "Fast Java & Spring Boot multi-module launcher and DAP group orchestrator for Zed."
repository = "https://github.com/vaspike/zed-java-launcher"
authors = ["River <vaspike@outlook.com>"]

[lib]
kind = "Rust"
version = "0.7.0"

[debug_adapters.java-launcher]
schema_path = "debug_adapter_schemas/java-launcher.json"

[slash_commands.launcher]
description = "Quick guide and actions for Java Launcher"
requires_argument = false
